# -*- coding: utf-8 -*-
"""Taxonomia unica de destino para brazilianlumber.com.

Regla de oro: una pieza de contenido = una URL = un canonical autorreferencial.
  - Categorias: ruta jerarquica limpia, sin /product-category/.
  - Productos:  SIEMPRE /product/{slug}/ plano, para que pertenecer a varias
                categorias NUNCA genere una segunda URL. Esta es la decision
                que corta de raiz el problema de canonicalizacion.
"""

# arbol de destino: ruta -> (titulo visible, ruta padre)
ARBOL = {
    "decking":                               ("Decking", None),
    "decking/tropical-hardwood":             ("Tropical Hardwood Decking", "decking"),
    "decking/tropical-hardwood/ipe":         ("Ipe Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/cumaru":      ("Cumaru Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/garapa":      ("Garapa Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/jatoba":      ("Jatoba Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/tigerwood":   ("Tigerwood Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/massaranduba":("Massaranduba Decking", "decking/tropical-hardwood"),
    "decking/tropical-hardwood/piquia":      ("Piquia Decking", "decking/tropical-hardwood"),
    "decking/composite":                     ("Composite Decking", "decking"),
    "decking/composite/trex":                ("Trex Composite Decking", "decking/composite"),
    "decking/composite/timbertech":          ("TimberTech Composite Decking", "decking/composite"),
    "decking/composite/azek":                ("AZEK Decking", "decking/composite"),
    "decking/composite/moistureshield":      ("MoistureShield Decking", "decking/composite"),
    "decking/composite/armadillo":           ("Armadillo Decking", "decking/composite"),
    "decking/composite/deckotech":           ("DeckoTech Composite Decking", "decking/composite"),
    "decking/composite/zuri":                ("Zuri Decking", "decking/composite"),
    "decking/composite/newtechwood":         ("NewTechWood Decking", "decking/composite"),
    "decking/pvc":                           ("PVC Decking", "decking"),
    "decking/thermally-modified":            ("Thermally Modified Decking", "decking"),
    "decking/thermally-modified/ayous":      ("Thermo Ayous Decking", "decking/thermally-modified"),
    "decking/thermally-modified/durathermo": ("Durathermo Decking", "decking/thermally-modified"),
    "decking/bamboo":                        ("Bamboo Decking", "decking"),
    "decking/deck-tiles":                    ("Deck Tiles", "decking"),

    "lumber":                                ("Dimensional Lumber", None),
    "lumber/tropical-hardwood":              ("Tropical Hardwood Lumber", "lumber"),
    "lumber/domestic-hardwood":              ("Domestic Hardwood Lumber", "lumber"),
    "lumber/softwood":                       ("Softwood Lumber", "lumber"),

    "cladding-siding":                       ("Cladding and Siding", None),
    "cladding-siding/wood-wall-panels":      ("Wood Wall Panels", "cladding-siding"),
    "cladding-siding/composite":             ("Composite Cladding", "cladding-siding"),
    "cladding-siding/battens-louvers":       ("Battens and Louvers", "cladding-siding"),

    "fencing-gates":                         ("Fencing and Gates", None),
    "fencing-gates/wood":                    ("Wood Fencing", "fencing-gates"),
    "fencing-gates/composite":               ("Composite Fencing", "fencing-gates"),
    "fencing-gates/gates":                   ("Gates", "fencing-gates"),

    "flooring":                              ("Flooring", None),
    "flooring/solid-hardwood":               ("Solid Hardwood Flooring", "flooring"),
    "flooring/engineered":                   ("Engineered Flooring", "flooring"),

    "slabs":                                 ("Live Edge Slabs", None),

    "landscaping":                           ("Landscaping", None),
    "landscaping/artificial-turf":           ("Artificial Turf", "landscaping"),
    "landscaping/artificial-ivy":            ("Artificial Ivy", "landscaping"),

    "accessories":                           ("Decking Accessories", None),
    "accessories/fasteners":                 ("Hidden Fasteners and Screws", "accessories"),
    "accessories/finishes-sealers":          ("Finishes, Oils and Sealers", "accessories"),
    "accessories/railing-cable":             ("Railing and Cable Systems", "accessories"),
    "accessories/substructure":              ("Substructure and Pedestals", "accessories"),
    "accessories/tools":                     ("Tools", "accessories"),
    "accessories/maintenance":               ("Cleaning and Maintenance", "accessories"),
}

# slug viejo de categoria (de cualquiera de los 3 portales) -> ruta nueva
MAP = {
    "tropical-hardwood": "decking/tropical-hardwood",
    "ipe": "decking/tropical-hardwood/ipe",
    "ipe-wood": "decking/tropical-hardwood/ipe",
    "cumaru": "decking/tropical-hardwood/cumaru",
    "best-priced-cumaru": "decking/tropical-hardwood/cumaru",
    "garapa": "decking/tropical-hardwood/garapa",
    "jatoba": "decking/tropical-hardwood/jatoba",
    "best-priced-jatoba": "decking/tropical-hardwood/jatoba",
    "tigerwood": "decking/tropical-hardwood/tigerwood",
    "massaranduba": "decking/tropical-hardwood/massaranduba",
    "massaranduba-wood": "decking/tropical-hardwood/massaranduba",
    "piquia": "decking/tropical-hardwood/piquia",

    "decking": "decking",
    "composite-decking": "decking/composite",
    "trex-decking": "decking/composite/trex",
    "transcend": "decking/composite/trex",
    "select": "decking/composite/trex",
    "enhance-naturals": "decking/composite/trex",
    "enhance-basics": "decking/composite/trex",
    "timbertech": "decking/composite/timbertech",
    "azek": "decking/composite/azek",
    "moistureshield": "decking/composite/moistureshield",
    "zuri": "decking/composite/zuri",
    "pvc-decking": "decking/pvc",
    "deckotech": "decking/composite/deckotech",
    "deckotech-decking": "decking/composite/deckotech",
    "terra": "decking/composite/deckotech",
    "terra-collection": "decking/composite/deckotech",
    "terra-best-priced-composite": "decking/composite/deckotech",
    "terra-essence": "decking/composite/deckotech",
    "essence-decking-collection": "decking/composite/deckotech",
    "prestige": "decking/composite/deckotech",
    "solara": "decking/composite/deckotech",
    "square-decking": "decking/composite/deckotech",
    "two-sides-decking": "decking/composite/deckotech",
    "grooved-two-sides": "decking/composite/deckotech",
    "stairboard": "decking/composite/deckotech",
    "modern": "decking/composite/deckotech",
    "refined": "decking/composite/deckotech",
    "enduring": "decking/composite/deckotech",

    "thermally-treated-wood": "decking/thermally-modified",
    "thermally-modified-wood": "decking/thermally-modified",
    "ayous": "decking/thermally-modified/ayous",
    "durathermo": "decking/thermally-modified/durathermo",
    "luna-wood": "decking/thermally-modified",

    "deck-tiles": "decking/deck-tiles",
    "cumaru-deck-tiles": "decking/deck-tiles",

    "cladding": "cladding-siding",
    "deckotech-cladding": "cladding-siding/composite",
    "composite-cladding": "cladding-siding/composite",
    "grid-cladding": "cladding-siding/composite",
    "grand-grid-cladding": "cladding-siding/composite",
    "corner-grid-cladding": "cladding-siding/composite",
    "shiplap-cladding": "cladding-siding/composite",
    "shiplap-corner-piece": "cladding-siding/composite",
    "finishing-trim": "cladding-siding/composite",
    "teto-vinilico": "cladding-siding/composite",
    "wood-wall-panels": "cladding-siding/wood-wall-panels",
    "cumaru-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "garapa-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "ipe-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "jatoba-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "poplar-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "red-oak-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "walnut-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "white-oak-wood-wall-panels": "cladding-siding/wood-wall-panels",
    "battens-and-louvers": "cladding-siding/battens-louvers",
    "deckotech-battens-and-louvers": "cladding-siding/battens-louvers",
    "aluminum-battens": "cladding-siding/battens-louvers",

    "fences-and-gates": "fencing-gates",
    "deckotech-fences-gates": "fencing-gates/composite",
    "silent-haven-fencing": "fencing-gates/composite",
    "grid-strong-fence-set": "fencing-gates/composite",
    "grid-strong-double-gate": "fencing-gates/gates",
    "smooth-shield-single-gate": "fencing-gates/gates",

    "domestic-hardwood": "lumber/domestic-hardwood",
    "oak": "lumber/domestic-hardwood",
    "walnut": "lumber/domestic-hardwood",
    "maple": "lumber/domestic-hardwood",
    "ash": "lumber/domestic-hardwood",
    "mahogany": "lumber/domestic-hardwood",
    "santos-mahogany": "lumber/domestic-hardwood",
    "sapele": "lumber/domestic-hardwood",
    "teak": "lumber/domestic-hardwood",
    "cypress": "lumber/softwood",
    "cedar": "lumber/softwood",
    "douglas-fir": "lumber/softwood",
    "spruce": "lumber/softwood",
    "yellow-pine": "lumber/softwood",
    "california-redwood": "lumber/softwood",
    "pine": "lumber/softwood",

    "live-edge-slabs": "slabs",
    "artificial-turf-and-ivy": "landscaping",
    "turf": "landscaping/artificial-turf",
    "ivy": "landscaping/artificial-ivy",
    "flooring": "flooring",
    "solid-unfinished-flooring": "flooring/solid-hardwood",

    "decking-accessories": "accessories",
    "grad-system": "accessories/substructure",
    "grad-concept": "accessories/substructure",
    "grad-concept-y-clip-on-system": "accessories/substructure",
    "clip-on-system": "accessories/fasteners",
    "hardwood-maintenance": "accessories/maintenance",
    "oil": "accessories/finishes-sealers",
    "sealer": "accessories/finishes-sealers",
    "wood-sealer": "accessories/finishes-sealers",
    "santos-mahogany-wood": "lumber/domestic-hardwood",
    "teak-wood": "lumber/domestic-hardwood",
    "mahogany-wood": "lumber/domestic-hardwood",
    "walnut-wood": "lumber/domestic-hardwood",
    "maple-wood": "lumber/domestic-hardwood",
    "artificial-grass": "landscaping/artificial-turf",
    "water-wood-sealer": "accessories/finishes-sealers",
}

# categorias que NO sobreviven como URL propia (vacias, promocionales o redundantes)
ELIMINAR = {"uncategorized", "hot-deals", "hots-deals-page"}

# especie -> rama de decking, para clasificar fichas de producto por su slug
ESPECIE = {
    "ipe": "decking/tropical-hardwood/ipe",
    "cumaru": "decking/tropical-hardwood/cumaru",
    "garapa": "decking/tropical-hardwood/garapa",
    "jatoba": "decking/tropical-hardwood/jatoba",
    "tigerwood": "decking/tropical-hardwood/tigerwood",
    "massaranduba": "decking/tropical-hardwood/massaranduba",
    "piquia": "decking/tropical-hardwood/piquia",
}
